config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root to: "home#index"
  resources :movies
  get 'rent_a_movie' => 'movies#make_a_rent'  
  post 'rent' => 'movies#rent'  
  #match '*path', to: 'home#index', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
	mount_uploader :photo, PhotoUploader 
	validates :title, presence: true
	validates :description, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	before_action :set_movie, only: [:show, :edit, :update, :destroy]

	def index
		@movies = Movie.all
		#@movies.order(id: :desc)		
		render json: @movies.order(title: :desc)
	end		

	def new
		@movie = Movie.new
		#@movie		
		render json: @movie
	end	

	def create
		#render plain: params[:movie].inspect
		@movie = Movie.new movie_params

		if @movie.save
			render json: @movie	
		end
		return 1 
	end

	def show
		render json: @movie
	end



	def edit
	end

	def update
		@movie.update movie_params
		#redirect_to @movie
		@movie = Movie.find params[:id]		
		render json: @movie
	end


	def destroy 
		@movie.destroy
		redirect_to movies_path
	end


	def make_a_rent
		
	end

	def rent
		palos = [ "Se completó la renta" , "No se le puede rentar porque tiene deudas"]
		num = palos.length
  		palo_aleat = rand(num)
  		output = { 'respuesta' => palos[palo_aleat] }.to_json
		render json: output
	end

	private
	def movie_params
		params.require(:movie).permit(:photo, :title, :description, :genre, :starring, :year)
	end

	def set_movie
		@movie = Movie.find params[:id]
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
	


<%= react_component('MoviesContainer', movies: @movies) %>

<% else %>
  


<%= image_tag("popcorn.png",  alt: "popcorn", class: "img-fluid") %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Videoclub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('logo.png') %>
    <%= stylesheet_link_tag    'application.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'index' %>
  </head>

  <body>

        <ul class="nav justify-content-end nav-devise">
      <%- if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Salir', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to ' Iniciar ', new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to ' Registrarme', new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>


    <div class="container">
<!--       <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p> -->
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb


<div class="container">
<%- if @movie.errors.any? %>
	<div class="alert alert-danger" role="alert">
	  Ah Ocurrido un error!
	</div>
<% end %>

	<div class="form-group">
		

		<%= form_for @movie, :html => {:multipart => true}, builder: CustomFormBuilder do |f| %>
		<%= f.label :title %>
		<%= f.text_field :title, class: 'form-control' %>
		<%= f.field_error :title %>
		<br>
		<%= f.label :description %>
		<%= f.text_field :description, class: 'form-control' %>
		<%= f.field_error :description %>
		<br>
		<%= f.label :year %>
		<%= f.date_field :year, class: 'form-control' %>
		<br>		
		<%= f.label :genre %>
		<%= f.text_field :genre, class: 'form-control' %>
		<br>
		<%= f.label :starring %>
		<%= f.text_field :starring, class: 'form-control' %>
		<br>
		<%= f.label :photo %>
		<%= f.file_field :photo %>
		<br>
		<%= f.submit 'Enviar', :class => 'btn btn-primary' %>
		<% end %>

	</div>
</div>

app/views/movies/_movie.html.erb
<!-- <div class="col-3">
	<div class="hvrbox">
		<img src="<%= movie.photo.medium.url %>" alt="Mountains" class="hvrbox-layer_bottom">
		<div class="hvrbox-layer_top">
			<div class="hvrbox-text">
			    <div class="text">           	
			    	<p class="textM"><span><%=  t('.Title') %>: </span> <%= movie.title %></p>
			        <p class="textM"><span><%=  t('.Description') %>: </span><%= movie.description %></p>
			        <p class="textM"><span><%=  t('.Genre') %>: </span><%= movie.genre %></p>
			        <p class="textM"><span><%=  t('.Starring') %>: </span><%= movie.starring %></p>			        
			        <p class="textM"><span><%=  t('.Year') %>: </span><%= movie.year %></p>
			    </div>
			</div>
		</div>
	</div>
		      <%= link_to t('.edit_link'), edit_movie_path(movie) %>
</div>
 -->


app/views/movies/edit.html.erb
<div class="container">
	
<p>Editar</p>
</div>
<%= render 'form' %> 

app/views/movies/index.html.erb
<div class="container">	
	
	<div class="row">		
		<%= render @movies %>
	</div>
</div>

app/views/movies/make_a_rent.html.erb
<% if user_signed_in? %>
	


<%= react_component('Cards') %> 


<% else %>




<%= image_tag("popcorn.png",  alt: "popcorn", class: "img-fluid") %>

<% end %>

app/views/movies/new.html.erb
<div class="container">
	
<p>hola</p>
</div>


<%= render 'form' %>

app/views/movies/show.html.erb
	  <%= image_tag @movie.photo.medium.url, class: 'figure-img img-fluid rounded' %>
<%= @movie.title %>
<%= @movie.description %>
<%= @movie.genre %>
<%= @movie.starring %>